from random import randint

import numpy as np
import pandas as pd
from sklearn.base import RegressorMixin, BaseEstimator
from sklearn.utils import _deprecate_positional_args
from sklearn.utils.validation import check_is_fitted

from ._make_names_string import make_names_string
from ._make_data_string import make_data_string, validate_x
from ._parse_model import parse_model
from ._variable_usage import get_variable_usage
from _cubist import _cubist, _predictions


class Cubist(RegressorMixin, BaseEstimator):
    """
    Cubist Regression Model (Public v2.07) developed by JR Quinlan.

    References:
    - https://www.rdocumentation.org/packages/Cubist/versions/0.3.0
    - https://www.rulequest.com/cubist-unix.html

    Parameters
    ----------
    n_rules : int, default=100
        Limit of the number of rules Cubist will build.

    n_committees : int, default=1
        Number of committees to construct. Each committee is a rule based model and beyond the first tries to correct 
        the prediction errors of the prior constructed model.

    unbiased : bool, default=False
        Should unbiased rules be used? Since Cubist minimizes the MAE of the predicted values, the rules may be biased 
        and the mean predicted value may differ from the actual mean. This is recommended when there are frequent 
        occurrences of the same value in a training dataset. Note that MAE may be slightly higher.

    extrapolation : float, default=1.0
        Adjusts how much rule predictions are adjusted to be consistent with 
        the training dataset.

    sample : float, default=0.0
        Percentage of the data set to be randomly selected for model building.

    random_state : int, default=randint(0, 4095)
        An integer to set the random seed for the C Cubist code.

    target_label : str, default="outcome"
        A label for the outcome variable. This is only used for printing rules.

    weights : array-like of shape (n_samples,)
        Optional vector of case weights that is the same length as y for how much each instance should contribute to 
        the model fit.

    neighbors : int, default=0
        Number between 0 and 9 for how many instances should be used to correct the rule-based prediction.

    verbose : int, default=0
        Should the Cubist output be printed?

    Attributes
    ----------
    names_string : str
        String for the Cubist model that describes the training dataset column names and their data types. This also 
        provides some Python environment information.

    model : str
        The Cubist model string generated by the C code.

    maxd : float

    variable_usage : pd.DataFrame
        Table of how training data variables are used in the Cubist model.

    rules : pd.DataFrame
        Table of the rules built by the Cubist model.

    coefficients : pd.DataFrame
        Table of the regression coefficients found by the Cubist model.

    variables : dict
        Information about all the variables passed to the model and those that were actually used.

    Examples
    --------
    >>> from cubist import Cubist
    >>> from sklearn.datasets import load_boston
    >>> from sklearn.model_selection import train_test_split
    >>> X, y = load_boston(return_X_y=True)
    >>> X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    >>> model = Cubist()
    >>> model.fit(X_train, y_train)
    >>> model.predict(X_test)
    >>> model.score(X_test, y_test)
    """
    @_deprecate_positional_args
    def __init__(self,
                 n_rules: int = 100,
                 n_committees: int = 1,
                 unbiased: bool = False,
                 extrapolation: float = 1.0,
                 sample: float = 0.0,
                 random_state: int = None, # randint(0, 4095),  # TODO fix this since its different from R
                 target_label: str = "outcome",
                 weights=None,
                 neighbors: int = 0,
                 verbose: int = 0):
        super().__init__()

        self.n_rules = n_rules
        self.n_committees = n_committees
        self.unbiased = unbiased
        self.extrapolation = extrapolation
        self.sample = sample
        self.random_state = random_state
        self.target_label = target_label
        self.weights = weights
        self.neighbors = neighbors
        self.verbose = verbose

    def fit(self, X, y):
        """
        Build a Cubist regression model from training set (X, y).

        Parameters
        ----------
        X : {array-like} of shape (n_samples, n_features)
            The training input samples.

        y : array-like of shape (n_samples,)
            The target values (Real numbers in regression).

        Returns
        -------
        self : object
        """
        # validate model parameters
        if self.n_rules < 1 or self.n_rules > 1000000:
            raise ValueError("number of rules must be between 1 and 1000000")

        if self.n_committees < 1 or self.n_committees > 100:
            raise ValueError("number of committees must be between 1 and 100")

        if self.extrapolation < 0.0 or self.extrapolation > 1.0:
            raise ValueError("extrapolation percentage must be between 0.0 and 1.0")

        if self.sample < 0.0 or self.sample > 1.0:
            raise ValueError("sampling percentage must be between 0.0 and 1.0")

        if self.random_state is None:
            self.random_state = randint(0, 4095) % 4095
        else:
            self.random_state = self.random_state % 4095

        if self.weights is not None and not isinstance(self.weights, (list, np.ndarray)):
            raise ValueError("case weights must be numeric")

        if not isinstance(self.neighbors, int):
            raise ValueError("Only an integer value for neighbors is allowed")
        if self.neighbors < 0 or self.neighbors > 10:
            raise ValueError("'neighbors' must be 0 or greater and 10 or less")

        # validate input data
        if X is None:
            raise ValueError("No training data passed to parameter X")
        if y is None:
            raise ValueError("No target/outcome data passed to parameter y")
        if not isinstance(y, (list, pd.Series, np.ndarray)):
            raise ValueError("Cubist requires a numeric target outcome")
        if not isinstance(y, pd.Series):
            y = pd.Series(y)

        # validate input data
        X = validate_x(X)
        X = X.reset_index(drop=True)
        y = y.reset_index(drop=True)

        # create the names and data strings required for cubist
        self.names_string = make_names_string(X, w=self.weights, label=self.target_label)
        self.data_string = make_data_string(X, y, w=self.weights)

        print(self.names_string)
        print(self.data_string)

        # call the C implementation of cubist
        self.model, output = _cubist(self.names_string.encode(),
                                     self.data_string.encode(),
                                     self.unbiased,
                                     b"yes",
                                     1,
                                     self.n_committees,
                                     self.sample,
                                     self.random_state,
                                     self.n_rules,
                                     self.extrapolation,
                                     b"1",
                                     b"1")

        # convert output from raw to strings
        self.model = self.model.decode()
        output = output.decode()

        # replace "__Sample" with "sample" if this is used in the model
        if "\n__Sample" in self.names_string:
            output = output.replace("__Sample", "sample")
            self.model = self.model.replace("__Sample", "sample")
            # clean model string when using reserved sample name
            self.model = self.model[:self.model.index("sample")] + \
                         self.model[self.model.index("entries"):]

        # raise cubist errors
        if "Error limit exceeded" in output:
            raise Exception(output)

        # print model output if using verbose output
        if self.verbose:
            print(output)

        # parse model contents and store useful information
        self.rules_, self.coefficients_, self.maxd_ = parse_model(self.model, X)

        # remove the maxd value from the model string
        initial_string = f'insts=\"1\" nn=\"1\" maxd=\"{int(self.maxd_)}\"'
        replacement_string = 'insts=\"0\"'
        self.model = self.model.replace(initial_string, replacement_string)

        # get the input data variable usage
        self.variable_usage_ = get_variable_usage(output, X)

        # get the names of columns that have no nan values
        is_na_col = ~self.coefficients_.isna().any()
        not_na_cols = self.coefficients_.columns[is_na_col].tolist()

        # skip the first three since these are always filled
        not_na_cols = not_na_cols[3:]

        # store a dictionary containing all the training dataset columns and those that were used by the model
        if self.rules_ is not None:
            used_variables = set(self.rules_["variable"]).union(
                set(not_na_cols)
            )
            self.variables_ = {"all": list(X.columns),
                               "used": list(used_variables)}

        return self

    def predict(self, X):
        """
        Predict Cubist regression target for X.

        Parameters
        ----------
        X : {array-like} of shape (n_samples, n_features)
            The input samples.

        Returns
        -------
        y : ndarray of shape (n_samples,)
            The predicted values.
        """
        check_is_fitted(self)
        # validate input data
        X = validate_x(X)
        X = X.reset_index(drop=True)

        if self.neighbors > 0:
            initial_string = "insts=\"0\""
            replacement_string = f"insts=\"1\" nn=\"{self.neighbors}\" maxd=\"{int(self.maxd_)}\""
            model = self.model.replace(initial_string, replacement_string)
        else:
            model = self.model

        # If there are case weights used during training, the C code will expect a column of weights in the new data but 
        # the values will be ignored. `makeDataFile` puts those last in the data when `cubist.default` is run, so we 
        # will add a column of NaN values at the end here
        if self.weights:
            X["case_weight_pred"] = np.nan

        # make data string for predictions
        data_string = make_data_string(X)
        
        # get cubist predictions from trained model
        pred, output = _predictions(data_string.encode(),
                                    self.names_string.encode(),
                                    self.data_string.encode(),
                                    model.encode(),
                                    np.zeros(X.shape[0]),
                                    b"1")

        # TODO: parse and handle errors in output
        if output:
            print(output.decode())
        return pred
